version = 0.1

[default.global.parameters]
stack_name = "mcp-gateway"
resolve_s3 = true
resolve_image_repos = true

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "mcp-gateway"
s3_prefix = "mcp-gateway"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
fail_on_empty_changeset = false
